spring:
  application:
    name: Song_CRUD

datasource:
  crud:
    jdbc-url: jdbc:mariadb://localhost:3306/mydatabase
    username: test
    password: userpassword
    maximum-pool-size: 10
    pool-name: HikariCP
    auto-commit: true

server:
  port: 8080


